#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

set -e

ZIMBRA_ROOT=/opt/zimbra
export TMP=${ZIMBRA_ROOT}/data/tmp

exec `which java` \
    -client \
    -Dhttps.protocols=TLSv1.2,TLSv1.3 \
    -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3 \
    -Dzimbra.home=${ZIMBRA_ROOT} \
    -Djava.library.path=${ZIMBRA_ROOT}/lib \
    -Djava.io.tmpdir=${TMP} \
    -classpath "${ZIMBRA_ROOT}/lib/jars:${ZIMBRA_ROOT}/lib/ext-common/*:${ZIMBRA_ROOT}/lib/jars/*" \
    -Dpython.cachedir.skip=true \
    org.python.util.jython \
     "$@"
